services:
  app_proxy:
    environment:
      APP_HOST: rfracas-open-webui_web_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/open-webui/open-webui:v0.6.18
    volumes:
      - ${APP_DATA_DIR}/data/open-webui:/app/backend/data
    restart: on-failure
