services:
  app_proxy:
    environment:
      APP_HOST: rfracas-nginx-proxy-manager_web_1
      APP_PORT: 81
      
  web:
    image: jc21/nginx-proxy-manager:2.12.6@sha256:dc9ccd92d8c534a4b9da7283c1b28f57b76d7980a45583270e5da492819f47c2
    hostname: rfracas-nginx-proxy-manager_web_1
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${APP_DATA_DIR}/data/npm-data:/data
      - ${APP_DATA_DIR}/data/letsencrypt:/etc/letsencrypt
    environment:
      PUID: 1000
      PGID: 1000
  
  docker-host:
    image: qoomon/docker-host:3.3.1@sha256:ec9d214d7fa88932e9186ca2f4419d44661376929931248525b08e7fa9e270f7
    hostname: $DEVICE_DOMAIN_NAME
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: on-failure