services:
  web:
    network_mode: host
    image: tailscale/tailscale:v1.86.2@sha256:847a2972485831aba32f1aa99af5866a212a598a621739da5300c48ccd6d989f
    restart: on-failure
    stop_grace_period: 1m
    command: sh -c 'apk add awake & tailscale web --listen 0.0.0.0:9240 & exec tailscaled --tun=userspace-networking'
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib
    container_name: rfracas_tailscale_web_1