services:
  app_proxy:
    environment:
      APP_HOST: rfracas-n8n_server_1
      APP_PORT: 5678
      # These webhook endpoints are protected using Basic or Header Auth
      # More details here: https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.webhook/
      PROXY_AUTH_WHITELIST: "/webhook-test/*,/webhook/*,/rest/*"

  server:
    image: n8nio/n8n:1.104.2@sha256:2537366a01590c499a4f2c9006da55cdda4c572fd2765a99f5687187ae1cd4be
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/home/node/.n8n
    stop_grace_period: 1m
    container_name: rfracas-n8n_server_1
    environment:
      - PUID=1000
      - PGID=1000
      - N8B_HOST=$DEVICE_DOMAIN_NAME
      - WEBHOOK_URL=https://umbrel-1.tail000ba5.ts.net
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=false
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
 